=== MaskedRiders/l2jtw_pvp_server/dp/dist/game/data/xsd/instance.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="instance">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element name="activityTime" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:attribute name="val" type="xs:positiveInteger" use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element name="allowSummon" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:attribute name="val" type="xs:boolean" use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element name="emptyDestroyTime" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:attribute name="val" type="xs:positiveInteger" use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element name="PvPInstance" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:attribute name="val" type="xs:boolean" use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element name="showTimer" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:attribute name="val" type="xs:boolean" use="required" />
						<xs:attribute name="increase" type="xs:boolean" use="optional" />
						<xs:attribute name="text" type="xs:normalizedString" use="optional" />
					</xs:complexType>
				</xs:element>
				<xs:element name="spawnPoint" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:attribute name="spawnX" type="xs:integer" use="required" />
						<xs:attribute name="spawnY" type="xs:integer" use="required" />
						<xs:attribute name="spawnZ" type="xs:integer" use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element name="doorlist" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="1">
							<xs:element name="door" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="doorId" type="xs:positiveInteger" use="required" />
									<xs:attribute name="default_status">
										<xs:simpleType>
											<xs:restriction base="xs:token">
												<xs:enumeration value="open" />
												<xs:enumeration value="close" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="random_time" type="xs:integer" />
									<xs:attribute name="open_time" type="xs:integer" />
									<xs:attribute name="close_time" type="xs:integer" />
									<xs:attribute name="level" type="xs:nonNegativeInteger" />
									<xs:attribute name="open_method" type="xs:nonNegativeInteger" />
									<xs:attribute name="targetable" type="xs:boolean" />
									<xs:attribute name="check_collision" type="xs:boolean" />
									<xs:attribute name="clanhall_id" type="xs:positiveInteger" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="spawnlist" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="unbounded">
							<xs:element name="group" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence minOccurs="1" maxOccurs="1">
										<xs:element name="spawn" minOccurs="1" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="amount" type="xs:positiveInteger" />
												<xs:attribute name="heading" type="xs:integer" use="required" />
												<xs:attribute name="npcId" type="xs:positiveInteger" use="required" />
												<xs:attribute name="onKillDelay" type="xs:nonNegativeInteger" />
												<xs:attribute name="respawn" type="xs:nonNegativeInteger" use="required" />
												<xs:attribute name="respawnRandom" type="xs:nonNegativeInteger" />
												<xs:attribute name="allowRandomWalk" type="xs:boolean" />
												<xs:attribute name="x" type="xs:integer" use="required" />
												<xs:attribute name="y" type="xs:integer" use="required" />
												<xs:attribute name="z" type="xs:integer" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name" type="xs:normalizedString" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="name" type="xs:normalizedString" use="required" />
			<xs:attribute name="ejectTime" type="xs:positiveInteger" />
			<xs:attribute name="allowRandomWalk" type="xs:boolean" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== MaskedRiders/l2jtw_pvp_server/dp/dist/game/data/instances/MonasteryOfSilence.xml
<?xml version="1.0" encoding="UTF-8"?>
<instance name="Monastery Of Silence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/instance.xsd">
	<activityTime val="30" />
	<allowSummon val="false" />
	<emptyDestroyTime val="1" />
	<spawnPoint spawnX="115983" spawnY="-87351" spawnZ="-3397" />
	<spawnlist>
		<group name="general">
			<!-- Eris's Evil Thoughts -->
			<spawn npcId="32792" x="120881" y="-86496" z="-3392" heading="49080" respawn="0" />
			<!-- Relic Guardian -->
			<spawn npcId="32803" x="85792" y="-249624" z="-8296" heading="0" respawn="0" />
			<!-- Teleport Control Device -->
			<spawn npcId="32817" x="86674" y="-249624" z="-8296" heading="32960" respawn="0" />
			<spawn npcId="32818" x="84909" y="-249625" z="-8296" heading="0" respawn="0" />
			<spawn npcId="32819" x="85792" y="-250512" z="-8296" heading="16400" respawn="0" />
			<spawn npcId="32820" x="85792" y="-248739" z="-8296" heading="49212" respawn="0" />
			<!-- Relic Watcher -->
			<spawn npcId="32804" x="88672" y="-249625" z="-8296" heading="32592" respawn="0" />
			<spawn npcId="32805" x="82528" y="-249616" z="-8296" heading="0" respawn="0" />
			<spawn npcId="32806" x="85788" y="-252497" z="-8296" heading="16852" respawn="0" />
			<spawn npcId="32807" x="85790" y="-246730" z="-8296" heading="48120" respawn="0" />
			<!-- Reading Desk -->
			<spawn npcId="32821" x="88664" y="-250731" z="-8320" heading="0" respawn="0" />
			<spawn npcId="32822" x="89775" y="-249620" z="-8320" heading="0" respawn="0" />
			<spawn npcId="32823" x="88662" y="-248537" z="-8320" heading="0" respawn="0" />
			<spawn npcId="32824" x="87584" y="-249626" z="-8320" heading="0" respawn="0" />
			<spawn npcId="32825" x="82528" y="-250734" z="-8320" heading="0" respawn="0" />
			<spawn npcId="32826" x="83630" y="-249615" z="-8320" heading="0" respawn="0" />
			<spawn npcId="32827" x="82525" y="-248525" z="-8320" heading="0" respawn="0" />
			<spawn npcId="32828" x="81441" y="-249621" z="-8320" heading="0" respawn="0" />
			<spawn npcId="32829" x="85793" y="-253611" z="-8320" heading="0" respawn="0" />
			<spawn npcId="32830" x="86904" y="-252506" z="-8320" heading="0" respawn="0" />
			<spawn npcId="32831" x="85789" y="-251429" z="-8320" heading="0" respawn="0" />
			<spawn npcId="32832" x="84712" y="-252512" z="-8320" heading="0" respawn="0" />
			<spawn npcId="32833" x="85790" y="-247830" z="-8320" heading="0" respawn="0" />
			<spawn npcId="32834" x="86888" y="-246734" z="-8320" heading="0" respawn="0" />
			<spawn npcId="32835" x="85793" y="-245640" z="-8320" heading="0" respawn="0" />
			<spawn npcId="32836" x="84705" y="-246730" z="-8320" heading="0" respawn="0" />
		</group>
	</spawnlist>
</instance>

=== MaskedRiders/l2jtw_pvp_server/dp/dist/game/data/instances/IceQueensCastleNormalBattle.xml
<?xml version="1.0" encoding="UTF-8"?>
<instance name="Ice Queen's Castle" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/instance.xsd">
	<activityTime val="120" />
	<allowSummon val="false" />
	<emptyDestroyTime val="600" />
	<spawnPoint spawnX="115717" spawnY="-125734" spawnZ="-3392" />
	<doorlist>
		<door doorId="23140101" />
	</doorlist>
	<spawnlist>
		<group name="general">
			<!-- Sirra -->
			<spawn npcId="32762" x="114766" y="-113141" z="-11200" heading="15956" respawn="0" />
		</group>
	</spawnlist>
</instance>
