=== MaskedRiders/l2jtw_pvp_server/dp/dist/game/data/xsd/items.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence maxOccurs="1" minOccurs="1">
				<xs:element name="item" maxOccurs="100" minOccurs="1">
					<xs:complexType>
						<xs:sequence maxOccurs="1" minOccurs="1">
							<xs:element name="set" maxOccurs="unbounded" minOccurs="1">
								<xs:complexType>
									<xs:attribute name="name" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:token">
												<xs:enumeration value="armor_type" />
												<xs:enumeration value="attack_range" />
												<xs:enumeration value="auto_destroy_time" />
												<xs:enumeration value="blessed" />
												<xs:enumeration value="bodypart" />
												<xs:enumeration value="capsuled_items" />
												<xs:enumeration value="change_weaponId" />
												<xs:enumeration value="crystal_count" />
												<xs:enumeration value="crystal_type" />
												<xs:enumeration value="damage_range" />
												<xs:enumeration value="default_action" />
												<xs:enumeration value="duration" />
												<xs:enumeration value="element_enabled" />
												<xs:enumeration value="enchant_enabled" />
												<xs:enumeration value="enchant4_skill" />
												<xs:enumeration value="enchanted" />
												<xs:enumeration value="equip_condition" />
												<xs:enumeration value="equip_reuse_delay" />
												<xs:enumeration value="ex_immediate_effect" />
												<xs:enumeration value="etcitem_type" />
												<xs:enumeration value="for_npc" />
												<xs:enumeration value="handler" />
												<xs:enumeration value="icon" />
												<xs:enumeration value="immediate_effect" />
												<xs:enumeration value="is_depositable" />
												<xs:enumeration value="is_destroyable" />
												<xs:enumeration value="is_dropable" />
												<xs:enumeration value="is_freightable" />
												<xs:enumeration value="is_magic_weapon" />
												<xs:enumeration value="is_oly_restricted" />
												<xs:enumeration value="is_premium" />
												<xs:enumeration value="is_questitem" />
												<xs:enumeration value="is_sellable" />
												<xs:enumeration value="is_stackable" />
												<xs:enumeration value="is_tradable" />
												<xs:enumeration value="isAttackWeapon" />
												<xs:enumeration value="isForceEquip" />
												<xs:enumeration value="item_skill" />
												<xs:enumeration value="allow_self_resurrection" />
												<xs:enumeration value="material" />
												<xs:enumeration value="mp_consume" />
												<xs:enumeration value="oncrit_chance" />
												<xs:enumeration value="oncrit_skill" />
												<xs:enumeration value="onmagic_chance" />
												<xs:enumeration value="onmagic_skill" />
												<xs:enumeration value="price" />
												<xs:enumeration value="random_damage" />
												<xs:enumeration value="recipe_id" />
												<xs:enumeration value="reduced_mp_consume" />
												<xs:enumeration value="reduced_soulshot" />
												<xs:enumeration value="reuse_delay" />
												<xs:enumeration value="shared_reuse_group" />
												<xs:enumeration value="soulshots" />
												<xs:enumeration value="spiritshots" />
												<xs:enumeration value="time" />
												<xs:enumeration value="unequip_skill" />
												<xs:enumeration value="use_condition" />
												<xs:enumeration value="useSkillDisTime" />
												<xs:enumeration value="useWeaponSkillsOnly" />
												<xs:enumeration value="weapon_type" />
												<xs:enumeration value="weight" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="val" type="xs:token" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="cond" maxOccurs="2" minOccurs="0">
								<xs:complexType>
									<xs:choice maxOccurs="1" minOccurs="1">
										<xs:element name="and" maxOccurs="1" minOccurs="0">
											<xs:complexType>
												<xs:choice maxOccurs="1" minOccurs="1">
													<xs:element name="player" maxOccurs="unbounded" minOccurs="1">
														<xs:complexType>
															<xs:attribute name="castle">
																<xs:simpleType>
																	<xs:restriction base="xs:integer">
																		<xs:minInclusive value="-1" />
																		<xs:maxInclusive value="9" />
																	</xs:restriction>
																</xs:simpleType>
															</xs:attribute>
															<xs:attribute name="clanHall" type="xs:normalizedString" />
															<xs:attribute name="class_id_restriction" type="xs:normalizedString" />
															<xs:attribute name="cloakStatus" type="xs:boolean" />
															<xs:attribute name="isHero" type="xs:boolean" />
															<xs:attribute name="level">
																<xs:simpleType>
																	<xs:restriction base="xs:positiveInteger">
																		<xs:minInclusive value="1" />
																		<xs:maxInclusive value="99" /> <!-- l2jtw fix Max_Level -->
																	</xs:restriction>
																</xs:simpleType>
															</xs:attribute>
															<xs:attribute name="pledgeClass">
																<xs:simpleType>
																	<xs:restriction base="xs:integer">
																		<xs:minInclusive value="-1" />
																		<xs:maxInclusive value="11" />
																	</xs:restriction>
																</xs:simpleType>
															</xs:attribute>
															<xs:attribute name="races" type="xs:token" />
															<xs:attribute name="subclass" type="xs:boolean" />
															<xs:attribute name="instanceId" type="xs:normalizedString" />
															<xs:attribute name="categoryType" type="xs:normalizedString" />
														</xs:complexType>
													</xs:element>
												</xs:choice>
											</xs:complexType>
										</xs:element>
										<xs:element name="player" maxOccurs="unbounded" minOccurs="1">
											<xs:complexType>
												<xs:attribute name="castle">
													<xs:simpleType>
														<xs:restriction base="xs:positiveInteger">
															<xs:minInclusive value="1" />
															<xs:maxInclusive value="9" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="chaotic" type="xs:boolean" />
												<xs:attribute name="clanHall" type="xs:normalizedString" />
												<xs:attribute name="class_id_restriction" type="xs:normalizedString" />
												<xs:attribute name="cloakStatus" type="xs:boolean" />
												<xs:attribute name="flyMounted" type="xs:boolean" />
												<xs:attribute name="fort" type="xs:integer" fixed="-1" />
												<xs:attribute name="insideZoneId" type="xs:normalizedString" />
												<xs:attribute name="instanceId" type="xs:normalizedString" />
												<xs:attribute name="isHero" type="xs:boolean" />
												<xs:attribute name="level">
													<xs:simpleType>
														<xs:restriction base="xs:positiveInteger">
															<xs:minInclusive value="1" />
															<xs:maxInclusive value="99" /> <!-- l2jtw fix Max_Level -->
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="levelRange" type="xs:token" />
												<xs:attribute name="pkCount" type="xs:nonNegativeInteger" fixed="0" />
												<xs:attribute name="pledgeClass">
													<xs:simpleType>
														<xs:restriction base="xs:integer">
															<xs:minInclusive value="-1" />
															<xs:maxInclusive value="11" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="races" type="xs:token" />
												<xs:attribute name="sex">
													<xs:simpleType>
														<xs:restriction base="xs:nonNegativeInteger">
															<xs:minInclusive value="0" />
															<xs:maxInclusive value="1" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="SiegeZone" type="xs:positiveInteger" fixed="126" />
												<xs:attribute name="vehicleMounted" type="xs:boolean" />
												<xs:attribute name="categoryType" type="xs:normalizedString" />
											</xs:complexType>
										</xs:element>
										<xs:element name="target" maxOccurs="unbounded" minOccurs="1">
											<xs:complexType>
												<xs:attribute name="levelRange" type="xs:token" />
												<xs:attribute name="categoryType" type="xs:normalizedString" />
											</xs:complexType>
										</xs:element>
									</xs:choice>
									<xs:attribute name="msgId" type="xs:positiveInteger" />
									<xs:attribute name="addName" type="xs:integer" fixed="1" />
								</xs:complexType>
							</xs:element>
							<xs:element name="for" maxOccurs="1" minOccurs="0">
								<xs:complexType>
									<xs:choice maxOccurs="unbounded" minOccurs="1">
										<xs:element name="add" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:attribute name="order" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:token">
															<xs:enumeration value="0x10" />
															<xs:enumeration value="0x40" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="stat" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:token">
															<xs:enumeration value="accCombat" />
															<xs:enumeration value="darkRes" />
															<xs:enumeration value="earthRes" />
															<xs:enumeration value="fireRes" />
															<xs:enumeration value="holyPower" />
															<xs:enumeration value="holyRes" />
															<xs:enumeration value="mAtk" />
															<xs:enumeration value="maxMp" />
															<xs:enumeration value="mDef" />
															<xs:enumeration value="pAtk" />
															<xs:enumeration value="pDef" />
															<xs:enumeration value="waterRes" />
															<xs:enumeration value="windRes" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="val" type="xs:decimal" use="required" />
											</xs:complexType>
										</xs:element>
										<xs:element name="enchant" maxOccurs="2" minOccurs="0">
											<xs:complexType>
												<xs:attribute name="order" type="xs:token" use="required" fixed="0x0C" />
												<xs:attribute name="stat" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:token">
															<xs:enumeration value="mAtk" />
															<xs:enumeration value="mDef" />
															<xs:enumeration value="pAtk" />
															<xs:enumeration value="pDef" />
															<xs:enumeration value="sDef" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="val" type="xs:integer" fixed="0" use="required" />
											</xs:complexType>
										</xs:element>
										<xs:element name="mul" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:attribute name="order">
													<xs:simpleType>
														<xs:restriction base="xs:token">
															<xs:enumeration value="0x08" />
															<xs:enumeration value="0x30" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="stat">
													<xs:simpleType>
														<xs:restriction base="xs:token">
															<xs:enumeration value="magicSuccRes" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="val" type="xs:decimal" />
											</xs:complexType>
										</xs:element>
										<xs:element name="set" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:attribute name="order" type="xs:token" fixed="0x08" use="required" />
												<xs:attribute name="stat" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:token">
															<xs:enumeration value="mAtk" />
															<xs:enumeration value="pAtk" />
															<xs:enumeration value="pAtkAngle" />
															<xs:enumeration value="pAtkRange" />
															<xs:enumeration value="pAtkSpd" />
															<xs:enumeration value="rCrit" />
															<xs:enumeration value="rShld" />
															<xs:enumeration value="sDef" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="val" type="xs:integer" use="required" />
											</xs:complexType>
										</xs:element>
										<xs:element name="sub" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:attribute name="order" type="xs:token" use="required" fixed="0x10" />
												<xs:attribute name="stat" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:token">
															<xs:enumeration value="rEvas" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="val" type="xs:integer" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:choice>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:positiveInteger">
									<xs:minInclusive value="1" />
									<xs:maxInclusive value="65535" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="name" type="xs:normalizedString" use="required" />
						<xs:attribute name="type" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:token">
									<xs:enumeration value="Armor" />
									<xs:enumeration value="EtcItem" />
									<xs:enumeration value="Weapon" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== MaskedRiders/l2jtw_pvp_server/dp/dist/game/data/stats/items/23300-23399_new.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/items.xsd">
	<item id="23347" name="武器用強化輔助石-R級" type="EtcItem">
		<table name="#Desc">維他命道具：強化R級武器時，可將機率提升10%的道具。僅限使用於強化3~9的道具。可以交易、丟棄或刪除的道具，也可以保管在個人倉庫。</table>
		<set name="icon" val="icon.ench_wp_potion_violet_i00" />
		<set name="etcitem_type" val="SCRL_INC_ENCHANT_PROP_WP" />
		<set name="material" val="PAPER" />
		<set name="weight" val="120" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="is_stackable" val="true" />
		<set name="is_premium" val="true" />
		<set name="handler" val="ItemSkills" />
		<set name="item_skill" val="9207-1" />
	</item>
	<item id="23348" name="防具用強化輔助石-R級" type="EtcItem">
		<table name="#Desc">維他命道具：強化R級防具時，可將機率提升15%的道具。僅限使用於強化3~9的道具；而連身防具則僅限使用於強化4~9的道具。可以交易、丟棄或刪除的道具，也可以保管在個人倉庫。</table>
		<set name="icon" val="icon.ench_am_potion_violet_i00" />
		<set name="etcitem_type" val="SCRL_INC_ENCHANT_PROP_AM" />
		<set name="material" val="PAPER" />
		<set name="weight" val="120" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="is_stackable" val="true" />
		<set name="is_premium" val="true" />
		<set name="handler" val="ItemSkills" />
		<set name="item_skill" val="9208-1" />
	</item>
</list>
