=== MaskedRiders/l2jtw_pvp_server/dp/dist/game/data/xsd/items.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence maxOccurs="1" minOccurs="1">
				<xs:element name="item" maxOccurs="100" minOccurs="1">
					<xs:complexType>
						<xs:sequence maxOccurs="1" minOccurs="1">
							<xs:element name="set" maxOccurs="unbounded" minOccurs="1">
								<xs:complexType>
									<xs:attribute name="name" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:token">
												<xs:enumeration value="armor_type" />
												<xs:enumeration value="attack_range" />
												<xs:enumeration value="auto_destroy_time" />
												<xs:enumeration value="blessed" />
												<xs:enumeration value="bodypart" />
												<xs:enumeration value="capsuled_items" />
												<xs:enumeration value="change_weaponId" />
												<xs:enumeration value="crystal_count" />
												<xs:enumeration value="crystal_type" />
												<xs:enumeration value="damage_range" />
												<xs:enumeration value="default_action" />
												<xs:enumeration value="duration" />
												<xs:enumeration value="element_enabled" />
												<xs:enumeration value="enchant_enabled" />
												<xs:enumeration value="enchant4_skill" />
												<xs:enumeration value="enchanted" />
												<xs:enumeration value="equip_condition" />
												<xs:enumeration value="equip_reuse_delay" />
												<xs:enumeration value="ex_immediate_effect" />
												<xs:enumeration value="etcitem_type" />
												<xs:enumeration value="for_npc" />
												<xs:enumeration value="handler" />
												<xs:enumeration value="icon" />
												<xs:enumeration value="immediate_effect" />
												<xs:enumeration value="is_depositable" />
												<xs:enumeration value="is_destroyable" />
												<xs:enumeration value="is_dropable" />
												<xs:enumeration value="is_freightable" />
												<xs:enumeration value="is_magic_weapon" />
												<xs:enumeration value="is_oly_restricted" />
												<xs:enumeration value="is_premium" />
												<xs:enumeration value="is_questitem" />
												<xs:enumeration value="is_sellable" />
												<xs:enumeration value="is_stackable" />
												<xs:enumeration value="is_tradable" />
												<xs:enumeration value="isAttackWeapon" />
												<xs:enumeration value="isForceEquip" />
												<xs:enumeration value="item_skill" />
												<xs:enumeration value="allow_self_resurrection" />
												<xs:enumeration value="material" />
												<xs:enumeration value="mp_consume" />
												<xs:enumeration value="oncrit_chance" />
												<xs:enumeration value="oncrit_skill" />
												<xs:enumeration value="onmagic_chance" />
												<xs:enumeration value="onmagic_skill" />
												<xs:enumeration value="price" />
												<xs:enumeration value="random_damage" />
												<xs:enumeration value="recipe_id" />
												<xs:enumeration value="reduced_mp_consume" />
												<xs:enumeration value="reduced_soulshot" />
												<xs:enumeration value="reuse_delay" />
												<xs:enumeration value="shared_reuse_group" />
												<xs:enumeration value="soulshots" />
												<xs:enumeration value="spiritshots" />
												<xs:enumeration value="time" />
												<xs:enumeration value="unequip_skill" />
												<xs:enumeration value="use_condition" />
												<xs:enumeration value="useSkillDisTime" />
												<xs:enumeration value="useWeaponSkillsOnly" />
												<xs:enumeration value="weapon_type" />
												<xs:enumeration value="weight" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="val" type="xs:token" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="cond" maxOccurs="2" minOccurs="0">
								<xs:complexType>
									<xs:choice maxOccurs="1" minOccurs="1">
										<xs:element name="and" maxOccurs="1" minOccurs="0">
											<xs:complexType>
												<xs:choice maxOccurs="1" minOccurs="1">
													<xs:element name="player" maxOccurs="unbounded" minOccurs="1">
														<xs:complexType>
															<xs:attribute name="castle">
																<xs:simpleType>
																	<xs:restriction base="xs:integer">
																		<xs:minInclusive value="-1" />
																		<xs:maxInclusive value="9" />
																	</xs:restriction>
																</xs:simpleType>
															</xs:attribute>
															<xs:attribute name="clanHall" type="xs:normalizedString" />
															<xs:attribute name="class_id_restriction" type="xs:normalizedString" />
															<xs:attribute name="cloakStatus" type="xs:boolean" />
															<xs:attribute name="isHero" type="xs:boolean" />
															<xs:attribute name="level">
																<xs:simpleType>
																	<xs:restriction base="xs:positiveInteger">
																		<xs:minInclusive value="1" />
																		<xs:maxInclusive value="99" /> <!-- l2jtw fix Max_Level -->
																	</xs:restriction>
																</xs:simpleType>
															</xs:attribute>
															<xs:attribute name="pledgeClass">
																<xs:simpleType>
																	<xs:restriction base="xs:integer">
																		<xs:minInclusive value="-1" />
																		<xs:maxInclusive value="11" />
																	</xs:restriction>
																</xs:simpleType>
															</xs:attribute>
															<xs:attribute name="races" type="xs:token" />
															<xs:attribute name="subclass" type="xs:boolean" />
															<xs:attribute name="instanceId" type="xs:normalizedString" />
															<xs:attribute name="categoryType" type="xs:normalizedString" />
														</xs:complexType>
													</xs:element>
												</xs:choice>
											</xs:complexType>
										</xs:element>
										<xs:element name="player" maxOccurs="unbounded" minOccurs="1">
											<xs:complexType>
												<xs:attribute name="castle">
													<xs:simpleType>
														<xs:restriction base="xs:positiveInteger">
															<xs:minInclusive value="1" />
															<xs:maxInclusive value="9" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="chaotic" type="xs:boolean" />
												<xs:attribute name="clanHall" type="xs:normalizedString" />
												<xs:attribute name="class_id_restriction" type="xs:normalizedString" />
												<xs:attribute name="cloakStatus" type="xs:boolean" />
												<xs:attribute name="flyMounted" type="xs:boolean" />
												<xs:attribute name="fort" type="xs:integer" fixed="-1" />
												<xs:attribute name="insideZoneId" type="xs:normalizedString" />
												<xs:attribute name="instanceId" type="xs:normalizedString" />
												<xs:attribute name="isHero" type="xs:boolean" />
												<xs:attribute name="level">
													<xs:simpleType>
														<xs:restriction base="xs:positiveInteger">
															<xs:minInclusive value="1" />
															<xs:maxInclusive value="99" /> <!-- l2jtw fix Max_Level -->
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="levelRange" type="xs:token" />
												<xs:attribute name="pkCount" type="xs:nonNegativeInteger" fixed="0" />
												<xs:attribute name="pledgeClass">
													<xs:simpleType>
														<xs:restriction base="xs:integer">
															<xs:minInclusive value="-1" />
															<xs:maxInclusive value="11" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="races" type="xs:token" />
												<xs:attribute name="sex">
													<xs:simpleType>
														<xs:restriction base="xs:nonNegativeInteger">
															<xs:minInclusive value="0" />
															<xs:maxInclusive value="1" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="SiegeZone" type="xs:positiveInteger" fixed="126" />
												<xs:attribute name="vehicleMounted" type="xs:boolean" />
												<xs:attribute name="categoryType" type="xs:normalizedString" />
											</xs:complexType>
										</xs:element>
										<xs:element name="target" maxOccurs="unbounded" minOccurs="1">
											<xs:complexType>
												<xs:attribute name="levelRange" type="xs:token" />
												<xs:attribute name="categoryType" type="xs:normalizedString" />
											</xs:complexType>
										</xs:element>
									</xs:choice>
									<xs:attribute name="msgId" type="xs:positiveInteger" />
									<xs:attribute name="addName" type="xs:integer" fixed="1" />
								</xs:complexType>
							</xs:element>
							<xs:element name="for" maxOccurs="1" minOccurs="0">
								<xs:complexType>
									<xs:choice maxOccurs="unbounded" minOccurs="1">
										<xs:element name="add" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:attribute name="order" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:token">
															<xs:enumeration value="0x10" />
															<xs:enumeration value="0x40" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="stat" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:token">
															<xs:enumeration value="accCombat" />
															<xs:enumeration value="darkRes" />
															<xs:enumeration value="earthRes" />
															<xs:enumeration value="fireRes" />
															<xs:enumeration value="holyPower" />
															<xs:enumeration value="holyRes" />
															<xs:enumeration value="mAtk" />
															<xs:enumeration value="maxMp" />
															<xs:enumeration value="mDef" />
															<xs:enumeration value="pAtk" />
															<xs:enumeration value="pDef" />
															<xs:enumeration value="waterRes" />
															<xs:enumeration value="windRes" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="val" type="xs:decimal" use="required" />
											</xs:complexType>
										</xs:element>
										<xs:element name="enchant" maxOccurs="2" minOccurs="0">
											<xs:complexType>
												<xs:attribute name="order" type="xs:token" use="required" fixed="0x0C" />
												<xs:attribute name="stat" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:token">
															<xs:enumeration value="mAtk" />
															<xs:enumeration value="mDef" />
															<xs:enumeration value="pAtk" />
															<xs:enumeration value="pDef" />
															<xs:enumeration value="sDef" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="val" type="xs:integer" fixed="0" use="required" />
											</xs:complexType>
										</xs:element>
										<xs:element name="mul" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:attribute name="order">
													<xs:simpleType>
														<xs:restriction base="xs:token">
															<xs:enumeration value="0x08" />
															<xs:enumeration value="0x30" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="stat">
													<xs:simpleType>
														<xs:restriction base="xs:token">
															<xs:enumeration value="magicSuccRes" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="val" type="xs:decimal" />
											</xs:complexType>
										</xs:element>
										<xs:element name="set" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:attribute name="order" type="xs:token" fixed="0x08" use="required" />
												<xs:attribute name="stat" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:token">
															<xs:enumeration value="mAtk" />
															<xs:enumeration value="pAtk" />
															<xs:enumeration value="pAtkAngle" />
															<xs:enumeration value="pAtkRange" />
															<xs:enumeration value="pAtkSpd" />
															<xs:enumeration value="rCrit" />
															<xs:enumeration value="rShld" />
															<xs:enumeration value="sDef" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="val" type="xs:integer" use="required" />
											</xs:complexType>
										</xs:element>
										<xs:element name="sub" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:attribute name="order" type="xs:token" use="required" fixed="0x10" />
												<xs:attribute name="stat" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:token">
															<xs:enumeration value="rEvas" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="val" type="xs:integer" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:choice>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:positiveInteger">
									<xs:minInclusive value="1" />
									<xs:maxInclusive value="65535" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="name" type="xs:normalizedString" use="required" />
						<xs:attribute name="type" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:token">
									<xs:enumeration value="Armor" />
									<xs:enumeration value="EtcItem" />
									<xs:enumeration value="Weapon" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== MaskedRiders/l2jtw_pvp_server/dp/dist/game/data/stats/items/40200-40299_new.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/items.xsd">
	<item id="40200" name="沙哈斗篷" type="Armor">
		<table name="#Plus">重力拳鬥士</table>
		<table name="#Desc">繼承沙哈之力的人所裝備的斗篷。魔法防禦力+40</table>
		<set name="icon" val="icon.vesper_cloack_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="back" />
		<set name="crystal_type" val="R" />
		<set name="material" val="CLOTH" />
		<set name="weight" val="220" />
		<for>
			<add order="0x10" stat="mDef" val="40" />
			<add order="0x10" stat="pDef" val="50" />
		</for>
	</item>
	<item id="40201" name="沙哈斗篷" type="Armor">
		<table name="#Plus">沙哈預知者</table>
		<table name="#Desc">繼承沙哈之力的人所裝備的斗篷。魔法防禦力+40</table>
		<set name="icon" val="icon.vesper_cloack_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="back" />
		<set name="crystal_type" val="R" />
		<set name="material" val="CLOTH" />
		<set name="weight" val="220" />
		<for>
			<add order="0x10" stat="mDef" val="40" />
			<add order="0x10" stat="pDef" val="50" />
		</for>
	</item>
</list>

=== MaskedRiders/l2jtw_pvp_server/dp/dist/game/data/stats/items/17500-17599_new.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/items.xsd">
	<item id="17526" type="EtcItem" name="武器強化卷軸-R級">
		<table name="#Desc">強化時，R級劍/單手、鈍器/單手、匕首、槍，以及其他類武器的物理攻擊力可提升6；劍/雙手、鈍器/雙手、二刀流、格鬥兵器/雙手、弩類武器的物理攻擊力可提升7；弓類武器的攻擊力可提升12；所有武器的魔法攻擊力可提升5。從強化+4開始，大幅提升物理攻擊力/魔法攻擊力。與一般武器相比，祝福的武器在所有層面上都有較大的增幅度。</table>
		<set name="icon" val="icon.scroll_of_enchant_weapon_i06" />
		<set name="default_action" val="SKILL_REDUCE" />
		<set name="etcitem_type" val="SCRL_ENCHANT_WP" />
		<set name="material" val="PAPER" />
		<set name="weight" val="120" />
		<set name="is_stackable" val="true" />
		<set name="is_oly_restricted" val="true" />
		<set name="handler" val="EnchantScrolls" />
		<set name="item_skill" val="9185-1" />
	</item>
	<item id="17527" type="EtcItem" name="防具強化卷軸-R級">
		<table name="#Desc">強化時，R級防具或飾品的物理防禦力可提升2，從強化+4開始將大幅提升物理防禦力。至+3為止能安全進行強化。防具強化+4以上時，隨著強化值HP也會提升。</table>
		<set name="icon" val="icon.scroll_of_enchant_armor_i06" />
		<set name="default_action" val="SKILL_REDUCE" />
		<set name="etcitem_type" val="SCRL_ENCHANT_AM" />
		<set name="material" val="PAPER" />
		<set name="weight" val="120" />
		<set name="is_stackable" val="true" />
		<set name="is_oly_restricted" val="true" />
		<set name="handler" val="EnchantScrolls" />
		<set name="item_skill" val="9186-1" />
	</item>
</list>

=== MaskedRiders/l2jtw_pvp_server/dp/dist/game/data/stats/items/19100-19199_new.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/items.xsd">
	<item id="19166" name="飾品用生命石-R級" type="EtcItem">
		<table name="#Desc">怪物內部的結石受到物理/魔法攻擊而僵硬的礦石。可成為精煉飾品的材料，等級85以上的角色可以使用。</table>
		<set name="icon" val="icon.r_mineral_unique_i00" />
		<set name="material" val="LIQUID" />
		<set name="weight" val="2" />
		<set name="is_stackable" val="true" />
		<cond msgId="113">
			<player level="85" />
		</cond>
	</item>
	<item id="19167" name="飾品用生命石-R95級" type="EtcItem">
		<table name="#Desc">怪物內部的結石受到物理/魔法攻擊而僵硬的礦石。可成為精煉飾品的材料，等級95以上的角色可以使用。</table>
		<set name="icon" val="icon.r95_mineral_unique_i00" />
		<set name="material" val="LIQUID" />
		<set name="weight" val="2" />
		<set name="is_stackable" val="true" />
		<cond msgId="113">
			<player level="95" />
		</cond>
	</item>
	<item id="19168" name="飾品用生命石-R99級" type="EtcItem">
		<table name="#Desc">怪物內部的結石受到物理/魔法攻擊而僵硬的礦石。可成為精煉飾品的材料，等級99以上的角色可以使用。</table>
		<set name="icon" val="icon.r99_mineral_unique_i00" />
		<set name="material" val="LIQUID" />
		<set name="weight" val="2" />
		<set name="is_stackable" val="true" />
		<cond msgId="113">
			<player level="99" />
		</cond>
	</item>
</list>

=== MaskedRiders/l2jtw_pvp_server/dp/dist/game/data/stats/items/17800-17899_new.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/items.xsd">
	<item id="17800" name="半獸人女性假髮-B" type="Armor">
		<set name="icon" val="BranchSys.icon.br_plastic_hair_f_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="hairall" />
		<set name="material" val="WOOD" />
		<set name="weight" val="10" />
		<cond msgId="1518">
			<and>
				<player races="ORC" />
				<player sex="1" />
			</and>
		</cond>
	</item>
	<item id="17803" name="半獸人男性巫醫假髮-A" type="Armor">
		<set name="icon" val="BranchSys.icon.br_plastic_hair_f_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="hairall" />
		<set name="material" val="WOOD" />
		<set name="weight" val="10" />
		<cond msgId="1518">
			<and>
				<player races="ORC" />
				<player sex="0" />
			</and>
		</cond>
	</item>
	<item id="17804" name="半獸人男性巫醫假髮-B" type="Armor">
		<set name="icon" val="BranchSys.icon.br_plastic_hair_f_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="hairall" />
		<set name="material" val="WOOD" />
		<set name="weight" val="10" />
		<cond msgId="1518">
			<and>
				<player races="ORC" />
				<player sex="0" />
			</and>
		</cond>
	</item>
	<item id="17807" name="半獸人女性巫醫假髮-A" type="Armor">
		<set name="icon" val="BranchSys.icon.br_plastic_hair_f_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="hairall" />
		<set name="material" val="WOOD" />
		<set name="weight" val="10" />
		<cond msgId="1518">
			<and>
				<player races="ORC" />
				<player sex="1" />
			</and>
		</cond>
	</item>
	<item id="17808" name="半獸人女性巫醫假髮-B" type="Armor">
		<set name="icon" val="BranchSys.icon.br_plastic_hair_f_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="hairall" />
		<set name="material" val="WOOD" />
		<set name="weight" val="10" />
		<cond msgId="1518">
			<and>
				<player races="ORC" />
				<player sex="1" />
			</and>
		</cond>
	</item>
	<item id="17811" name="闇天使男性假髮-A" type="Armor">
		<set name="icon" val="BranchSys.icon.br_plastic_hair_f_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="hairall" />
		<set name="material" val="WOOD" />
		<set name="weight" val="10" />
		<cond msgId="1518">
			<and>
				<player races="KAMAEL" />
				<player sex="0" />
			</and>
		</cond>
	</item>
	<item id="17812" name="闇天使男性假髮-B" type="Armor">
		<set name="icon" val="BranchSys.icon.br_plastic_hair_f_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="hairall" />
		<set name="material" val="WOOD" />
		<set name="weight" val="10" />
		<cond msgId="1518">
			<and>
				<player races="KAMAEL" />
				<player sex="0" />
			</and>
		</cond>
	</item>
	<item id="17815" name="闇天使女性假髮-A" type="Armor">
		<set name="icon" val="BranchSys.icon.br_plastic_hair_f_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="hairall" />
		<set name="material" val="WOOD" />
		<set name="weight" val="10" />
		<cond msgId="1518">
			<and>
				<player races="KAMAEL" />
				<player sex="1" />
			</and>
		</cond>
	</item>
	<item id="17816" name="闇天使女性假髮-B" type="Armor">
		<set name="icon" val="BranchSys.icon.br_plastic_hair_f_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="hairall" />
		<set name="material" val="WOOD" />
		<set name="weight" val="10" />
		<cond msgId="1518">
			<and>
				<player races="KAMAEL" />
				<player sex="1" />
			</and>
		</cond>
	</item>
</list>

=== MaskedRiders/l2jtw_pvp_server/dp/dist/game/data/stats/items/33400-33499_new.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/items.xsd">
	<item id="33478" name="破滅武器強化卷軸-R級" type="EtcItem">
		<table name="#Desc">強化時，R級劍/單手、鈍器/單手、匕首、槍，以及其他類武器的物理攻擊力可提升6；劍/雙手、鈍器/雙手、二刀流、格鬥兵器/雙手、弩類武器的物理攻擊力可提升7；弓類武器的攻擊力可提升12；所有武器的魔法攻擊力可提升5。從強化+4開始，大幅提升物理攻擊力/魔法攻擊力。與一般武器相比，祝福的武器在所有層面上都有較大的增幅度。強化失敗時，藉由破滅女神之力，現有的裝備雖不會被結晶化，但將維持現有的強化數值。無法用於強化+15以上的防具。</table>
		<set name="icon" val="icon.scroll_of_enchant_weapon_i06" />
		<set name="default_action" val="SKILL_REDUCE" />
		<set name="etcitem_type" val="ANCIENT_CRYSTAL_ENCHANT_WP" /> <!-- l2jtw : 603 -->
		<set name="material" val="PAPER" />
		<set name="is_stackable" val="true" />
		<set name="is_premium" val="true" />
		<set name="is_oly_restricted" val="true" />
		<set name="handler" val="EnchantScrolls" />
		<set name="item_skill" val="12872-1" />
	</item>
	<item id="33479" name="破滅防具強化卷軸-R級" type="EtcItem">
		<table name="#Desc">強化時，R級防具或飾品的物理防禦力可提升2，從強化+4開始大幅提升物理防禦力。至+3為止能安全進行強化。防具強化+4以上時，隨著強化值HP也會提升。強化失敗時，藉由破滅女神之力，現有的裝備雖不會被結晶化，但將維持現有的強化數值。無法用於強化+6以上的防具。</table>
		<set name="icon" val="icon.scroll_of_enchant_armor_i06" />
		<set name="default_action" val="SKILL_REDUCE" />
		<set name="etcitem_type" val="ANCIENT_CRYSTAL_ENCHANT_AM" /> <!-- l2jtw : 603 -->
		<set name="material" val="PAPER" />
		<set name="is_stackable" val="true" />
		<set name="is_premium" val="true" />
		<set name="is_oly_restricted" val="true" />
		<set name="handler" val="EnchantScrolls" />
		<set name="item_skill" val="12873-1" />
	</item>
</list>

=== MaskedRiders/l2jtw_pvp_server/dp/dist/game/data/stats/items/30300-30399_new.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/items.xsd">
	<item id="30310" name="亞貝里烏斯斗篷" type="Armor">
		<table name="#Plus">席格爾騎士</table>
		<table name="#Desc">繼承古代巨人-亞貝里烏斯之力的人所裝備的斗篷。魔法防禦+40。</table>
		<set name="icon" val="icon.vesper_cloack_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="back" />
		<set name="crystal_type" val="R" />
		<set name="material" val="CLOTH" />
		<set name="weight" val="220" />
		<for>
			<add order="0x10" stat="mDef" val="40" />
			<add order="0x10" stat="pDef" val="50" />
		</for>
	</item>
	<item id="30311" name="薩菲洛斯斗篷" type="Armor">
		<table name="#Plus">提爾鬥士</table>
		<table name="#Desc">繼承古代巨人-薩菲洛斯之力的人所裝備的斗篷。魔法防禦+40。</table>
		<set name="icon" val="icon.vesper_cloack_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="back" />
		<set name="crystal_type" val="R" />
		<set name="material" val="CLOTH" />
		<set name="weight" val="220" />
		<for>
			<add order="0x10" stat="mDef" val="40" />
			<add order="0x10" stat="pDef" val="50" />
		</for>
	</item>
	<item id="30312" name="凱修納格斗篷" type="Armor">
		<table name="#Plus">歐瑟遊俠</table>
		<table name="#Desc">繼承古代巨人-凱修納格之力的人所裝備的斗篷。魔法防禦+40。</table>
		<set name="icon" val="icon.vesper_cloack_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="back" />
		<set name="crystal_type" val="R" />
		<set name="material" val="CLOTH" />
		<set name="weight" val="220" />
		<for>
			<add order="0x10" stat="mDef" val="40" />
			<add order="0x10" stat="pDef" val="50" />
		</for>
	</item>
	<item id="30313" name="克倫畢斯特斗篷" type="Armor">
		<table name="#Plus">尤爾弓手</table>
		<table name="#Desc">繼承古代巨人-克倫畢斯特之力的人所裝備的斗篷。魔法防禦+40。</table>
		<set name="icon" val="icon.vesper_cloack_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="back" />
		<set name="crystal_type" val="R" />
		<set name="material" val="CLOTH" />
		<set name="weight" val="220" />
		<for>
			<add order="0x10" stat="mDef" val="40" />
			<add order="0x10" stat="pDef" val="50" />
		</for>
	</item>
	<item id="30314" name="索特克里格斗篷" type="Armor">
		<table name="#Plus">菲歐巫師</table>
		<table name="#Desc">繼承古代巨人-索特克里格之力的人所裝備的斗篷。魔法防禦+40。</table>
		<set name="icon" val="icon.vesper_cloack_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="back" />
		<set name="crystal_type" val="R" />
		<set name="material" val="CLOTH" />
		<set name="weight" val="220" />
		<for>
			<add order="0x10" stat="mDef" val="40" />
			<add order="0x10" stat="pDef" val="50" />
		</for>
	</item>
	<item id="30315" name="納比亞羅普斗篷" type="Armor">
		<table name="#Plus">維因召喚士</table>
		<table name="#Desc">繼承古代巨人-納比亞羅普之力的人所裝備的斗篷。魔法防禦+40。</table>
		<set name="icon" val="icon.vesper_cloack_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="back" />
		<set name="crystal_type" val="R" />
		<set name="material" val="CLOTH" />
		<set name="weight" val="220" />
		<for>
			<add order="0x10" stat="mDef" val="40" />
			<add order="0x10" stat="pDef" val="50" />
		</for>
	</item>
	<item id="30316" name="拉伊斯特斗篷" type="Armor">
		<table name="#Plus">伊斯法師</table>
		<table name="#Desc">繼承古代巨人-拉伊斯特之力的人所裝備的斗篷。魔法防禦+40。</table>
		<set name="icon" val="icon.vesper_cloack_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="back" />
		<set name="crystal_type" val="R" />
		<set name="material" val="CLOTH" />
		<set name="weight" val="220" />
		<for>
			<add order="0x10" stat="mDef" val="40" />
			<add order="0x10" stat="pDef" val="50" />
		</for>
	</item>
	<item id="30317" name="拉奇西斯斗篷" type="Armor">
		<table name="#Plus">艾羅牧師</table>
		<table name="#Desc">繼承古代巨人-拉奇西斯之力的人所裝備的斗篷。魔法防禦+40。</table>
		<set name="icon" val="icon.vesper_cloack_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="back" />
		<set name="crystal_type" val="R" />
		<set name="material" val="CLOTH" />
		<set name="weight" val="220" />
		<for>
			<add order="0x10" stat="mDef" val="40" />
			<add order="0x10" stat="pDef" val="50" />
		</for>
	</item>
	<item id="30381" name="武器用強化輔助石-R級" type="EtcItem">
		<table name="#Desc">強化R級武器時，可將機率提升10%的道具。僅限使用於強化3~9的道具。無法交易、丟棄、刪除的道具，但可以保管在個人倉庫。</table>
		<set name="icon" val="icon.ench_wp_potion_violet_i00" />
		<set name="etcitem_type" val="SCRL_INC_ENCHANT_PROP_WP" />
		<set name="material" val="PAPER" />
		<set name="weight" val="120" />
		<set name="is_stackable" val="true" />
		<set name="is_oly_restricted" val="true" />
		<set name="handler" val="ItemSkills" />
		<set name="item_skill" val="9207-1" />
	</item>
	<item id="30382" name="防具用強化輔助石-R級" type="EtcItem">
		<table name="#Desc">強化R級防具時，可將機率提升15%的道具。僅限使用於強化3~9的道具；而連身防具則僅限使用於強化4~9的道具。無法交易、丟棄、刪除的道具，但可以保管在個人倉庫。</table>
		<set name="icon" val="icon.ench_am_potion_violet_i00" />
		<set name="etcitem_type" val="SCRL_INC_ENCHANT_PROP_AM" />
		<set name="material" val="PAPER" />
		<set name="weight" val="120" />
		<set name="is_stackable" val="true" />
		<set name="is_oly_restricted" val="true" />
		<set name="handler" val="ItemSkills" />
		<set name="item_skill" val="9208-1" />
	</item>
</list>
